# permissions for end users to edit monitorings.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: monitoring-editor-role
rules:
- apiGroups:
  - rt.francescol96.univr
  resources:
  - monitorings
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - rt.francescol96.univr
  resources:
  - monitorings/status
  verbs:
  - get
