# permissions for end users to view monitorings.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: monitoring-viewer-role
rules:
- apiGroups:
  - rt.francescol96.univr
  resources:
  - monitorings
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - rt.francescol96.univr
  resources:
  - monitorings/status
  verbs:
  - get
