apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: modify-monitorrtapi
rules:
  - apiGroups: ["rt.francescol96.univr"]
    resources:
      - monitorings
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
